# Generated by Django 4.2.15 on 2024-08-17 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='charity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='charities.charity'),
        ),
    ]
